application: rss-xmpp
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static
- url: /cron/feeding
  script: feedcrawler.py
- url: .*
  script: main.py

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

